CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS articles (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    title VARCHAR(150) NOT NULL,
    content TEXT NOT NULL,
    created_by INTEGER NOT NULL
);
